name: flappy_bird_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  flame: ^1.10.0
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.6
  provider: ^6.0.5
  game: ^0.0.4
 
  path_provider: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
  fonts:
    - family: Game     
      fonts:
        - asset: assets/fonts/Game.ttf
